services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: haupcar
    ports:
      - '5432:5432'
    volumes:
      - haupcar-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'

volumes:
  haupcar-db-data:

networks:
  default:
    name: haupcar
